version: '3.8'

services:
  zania-backend:
    build: .
    container_name: zania-bot-container
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: on-failure